apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}-pod
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            {{- if .Values.createConfigMap }}
            - configMapRef:
                name: {{ .Release.Name }}-config
            {{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          volumeMounts:
            {{- if .Values.createPVC }}
            - mountPath: /var/lib/application/data
              name: app-pv-storage
            {{- end }}
      volumes:
        {{- if .Values.createPVC }}
        - name: app-pv-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        {{- end }}
  replicas: {{ .Values.replicas }}  # Use the replicas value from values.yaml
