apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}  # This selects ClusterIP or NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}  # Dynamically set targetPort
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}  # Used only for NodePort type
      {{- end }}
  selector:
    app: {{ .Release.Name }}
